UI made into Rust default feature, in case you do not want x11 common library
wiiznokes/fan-control pull request #140
Opened 2024-06-21 20:09 UTC by Xavantex

Changes UI dependency into a Rust feature that can be turned off at compile time.
This loses the libxkbcommon dependency, allowing most common headless environments to run binary.

Only tested to run with a test config and all the arg flags.
No hardware available currently to test on personally.

2024-06-21 20:14 UTC, Xavantex commented
https://github.com/wiiznokes/fan-control/issues/138#issuecomment-2183037073

New pull request as given go ahead :)

2024-06-22 19:02 UTC, wiiznokes requested changes
lgtm, expect the missing ';'

2024-06-22 19:02 UTC, wiiznokes commented on src/main.rs
> +    cli::run_cli(app_state)
```suggestion
    cli::run_cli(app_state);
    
```

2024-06-22 19:03 UTC, wiiznokes approved these changes

2024-06-22 19:05 UTC, wiiznokes commented on src/main.rs
> +
```suggestion

```

2024-06-22 19:12 UTC, merged